### ISSUE TITLE
Quantity Strings (Plurals)

### ISSUE THREAD

**Issue by ghost** [franciscofranco/5217-localisation#8]
Just take a look here:
https://developer.android.com/guide/topics/resources/string-resource.html#Plurals

**Comment by franciscofranco** [comment]
Yeah I know, it's planned for the next 1.1 release coming up this next Tuesday!

**Comment by franciscofranco** [comment]
Fixed https://github.com/franciscofranco/5217-localisation/commit/659bc19654b1a64cf1847e23f2d8f715328cb3fd
